---
title: "fire.Rmd"
author: "Rachel Pekelney & Joshua Hauser"
date: "11/28/2021"
output: html_document
---

```{r options, include= FALSE, warning = FALSE}
library(tmap)      #interactive maps, raster + vector layers
library(terra)       # Successor to the raster library
library(tidyverse)   # our old friend
library(sf)   # to work with simple features (vector) data
library(rosm) # to work with OSM data
library(prettymapr)
library(yaps)
library(rgdal)
library(raster)
```  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Fire perimeters in the ICB
https://frap.fire.ca.gov/frap-projects/fire-perimeters/

```{r, results='hide}
dir.create("../data/fireperimeters")
download.file("https://frap.fire.ca.gov/media/50dgwqrb/fire20_1.zip", "../data/fireperimeters/fire20_1.zip")
unzip("../data/fireperimeters/fire20_1.zip", 
      exdir = "../data/fireperimeters/fireperimeters")
```

```{r}
#can filter by NPS and YNP easily I think. I think to get the ICB fires though we should just manually select them out of the table from "FIRE_NAME"
fireperimeters_nad83 = st_read("../data/fireperimeters/fireperimeters/fire20_1.gdb")

# re-project to same CRS as Landsat imagery: WGS 84 / UTM Zone 10N
# load Landsat raster first to have CRS available for reference
landsat_raster_b4 <- rast("LC08_L1TP_042034_20210915_20210925_02_T1_B4.TIF")

fireperimeters = st_transform(fireperimeters_nad83, crs(landsat_raster_b4))
```

```{r}
# will need to re-project fire perimeters to different CRS: WGS 84 / UTM Zone 10N
yos_fires = as.tibble(fireperimeters) %>%
  filter(UNIT_ID == "YNP") %>%
  filter(YEAR_ > 1971) %>%
  arrange(YEAR_)
yos_fires
```


```{r, , results=hide}
# unzipping boundary for Yosemite National Park

dir.create("../data/yosemiteboundary")
download.file("https://irma.nps.gov/DataStore/DownloadFile/427871", "../data/yosemiteboundary/Yose_Boundary.zip")
unzip("../data/yosemiteboundary/Yose_Boundary.zip", 
      exdir = "../data/yosemiteboundary/yosemiteboundary")

yos_bound_nad83 = st_read("../data/yosemiteboundary/yosemiteboundary")

# re-project to same CRS as Landsat imagery: WGS 84 / UTM Zone 10N
yos_bound = st_transform(yos_bound_nad83, crs(landsat_raster_b4))
```

```{r}
# Landsat rasters for 9/15/21
landsat_raster_b4 <- rast("LC08_L1TP_042034_20210915_20210925_02_T1_B4.TIF")
landsat_raster_b5 <- rast("LC08_L1TP_042034_20210915_20210925_02_T1_B5.TIF")

# projected so everything is in WGS 84 / UTM Zone 10N
icb_shp_nad83 <- st_read("ill_wtrshd_nad83.shp")
icb_shp <- st_transform(icb_shp_nad83, crs(landsat_raster_b4))
# confirming that it successfully re-projected 
st_crs(icb_shp)

# for Landsat 8 [B4 = Red and B5 = NIR]
# NDVI = (NIR - Red) / (NIR + Red)
landsat_ndvi <- (landsat_raster_b5 - landsat_raster_b4) / (landsat_raster_b5 + landsat_raster_b4)

# plot the data
tm_shape(landsat_ndvi, bbox = st_bbox(icb_shp)) + tm_raster(midpoint = 0, title="NDVI Index Value") + 
  tm_shape(icb_shp) + tm_polygons(alpha=0) +
  tm_compass(size=1) + tm_scale_bar() + 
  tm_layout(main.title="NDVI in ICB (2021)", legend.outside = TRUE)

```

```{r}
# Landsat rasters for 9/16/1972
landsat72_raster_b5 <- rast("LM01_L1TP_045034_19720916_20200909_02_T2_B5.TIF")
landsat72_raster_b7 <- rast("LM01_L1TP_045034_19720916_20200909_02_T2_B7.TIF")

# for Landsat 1-3 [B5 = red and B7 = NIR] 
# NDVI = (NIR - Red) / (NIR + Red)
landsat_ndvi72 <- (landsat72_raster_b7 - landsat72_raster_b5) / (landsat72_raster_b7 + landsat72_raster_b5)

# plot the data
tm_shape(landsat_ndvi72, bbox = st_bbox(icb_shp), title="NDVI") + tm_raster(midpoint = 0, title="NDVI Index Value") + 
  tm_shape(icb_shp) + tm_polygons(alpha=0) +
  tm_compass(size=1) + tm_scale_bar() + 
  tm_layout(main.title="NDVI in ICB (1972)", legend.outside = TRUE)

```

```{r}
# histogram of NDVI 2021
cropped21 = crop(landsat_ndvi, icb_shp)
cropped72 = crop(landsat_ndvi72, icb_shp)

hist(cropped21 / (531*590)),
  main = "NDVI: Distribution of pixels\n Illilouette Creek Basin 2021",
  col = "springgreen",
  xlab = "NDVI Index Value")

# histogram of NDVI 1972
hist(cropped72,
     add=T,
  main = "NDVI: Distribution of pixels\n Illilouette Creek Basin 1972",
  col = "springgreen",
  xlab = "NDVI Index Value")

df21 = as.data.frame(cropped21) %>%
  mutate(range = cut(LC08_L1TP_042034_20210915_20210925_02_T1_B5, c(-1, -.9, -.8, -.7, -.6, -.5, -.4, -.3, -.2, -.1, 0, .1, .2, .3, .4, .5, .6, .7, .8, .9, 1))) %>%
  group_by(range) %>%
  summarise(n=n()) %>%
  mutate(percent = 100 * n/(531* 590))


df72 = as.data.frame(cropped72) %>%
  mutate(range = cut(LM01_L1TP_045034_19720916_20200909_02_T2_B7, c(-1, -.9, -.8, -.7, -.6, -.5, -.4, -.3, -.2, -.1, 0, .1, .2, .3, .4, .5, .6, .7, .8, .9, 1))) %>%
  group_by(range) %>%
  summarise(n=n()) %>%
  mutate(percent = 100 * n/(265*295))
  
  

hist(df21$percent,
  main = "NDVI: Distribution of pixels\n Illilouette Creek Basin 2021",
  col = "springgreen",
  xlab = "NDVI Index Value")

# histogram of NDVI 1972
hist(df72,
     add=T,
  main = "NDVI: Distribution of pixels\n Illilouette Creek Basin 1972",
  col = "springgreen",
  xlab = "NDVI Index Value")

df21 %>%
  ggplot(aes(x = range)) + geom_histogram() + ggtitle("Histogram of NDVI 2021")


as.data.frame(cropped72) %>%
  ggplot(aes(x = LM01_L1TP_045034_19720916_20200909_02_T2_B7)) + geom_histogram() + ggtitle("Histogram of NDVI 1972")

```

Fire Perimeters Mapped onto true color Landsat basemap
```{r}
landsat_refl_21 = rast("LC08_L1TP_042034_20210915_20210925_02_T1_refl.tif")
rgb = brick(landsat_refl_21)
rgb_stack = stack(rgb)

cropped = crop(rgb, yos_bound)
plotRGB(cropped)

fire_shp = st_read("California_Wildland_Fire_Perimeters_(All)/California_Wildland_Fire_Perimeters_(All).shp")
fire_shp_reproj = st_transform(fire_shp, crs(landsat_raster_b4))

keep <- st_is_valid(fire_shp_reproj)

tm_shape(cropped, bbox = st_bbox(yos_bound)) + tm_rgb() +
  fire_shp_reproj %>% filter(keep) %>% tm_shape(name="Fire Perimeters", bbox = st_bbox(yos_bound)) + tm_polygons(col = "yellow", border.col = "red", alpha = 0.1, lwd = 1) + 
  tm_shape(yos_bound, name="Yosemite Nat'l Park") + tm_polygons(border.col = "blue",  alpha = 0) + 
  tm_shape(icb_shp, name="ICB") + tm_polygons(border.col = "white",  alpha = 0) +
  tm_compass(size=1) + tm_scale_bar() + 
  tm_layout(legend.outside=TRUE, 
            main.title="Fire Perimeters in Yosemite National Park",
            legend.text.size = 0.5,
            legend.position = c("left", "bottom"))

```


```{r}
# NAIP raster
naip_raster <- rast('m_3711920_se_11_060_20200804.jp2')

#trying NDVI calculation
naip_multispectral_st <- stack(naip_raster)
naip_multispectral_br <- brick(naip_multispectral_st)

naip_ndvi <- (naip_multispectral_br[[4]] - naip_multispectral_br[[1]]) / (naip_multispectral_br[[4]] + naip_multispectral_br[[1]])
cropped_naip <- crop(naip_ndvi, yos_bound)

# plot the data
plot(cropped_naip,
     main = "NDVI of Illilouette Creek Basin",
     axes = FALSE, box = FALSE)

```


Landsat 1-3 
Band 5 = red
Band 7 = NIR
date 9/16/1972

Landsat 8
Band 4 = red
Band 5 = NIR
date 9/15/2021
